### ISSUE TITLE
Semgrep version not appearing

### ISSUE THREAD

**Issue by kaabmuhammad** [RiverSafeUK/eze-cli#102]
Supporting information --

running command 'docker run --rm returntocorp/semgrep semgrep scan --version'
 std output: '1.2.0
' error output: '
A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

**Comment by shyamriversafe** [comment]
It's working now. The latest version it is pulling is 1.2.1

**Comment by Anthony-Mckale** [comment]
in peer review

**Comment by Anthony-Mckale** [comment]
https://github.com/RiverSafeUK/eze-cli/pull/103/

**Comment by Anthony-Mckale** [comment]
done

tested with `eze tools list --include-version`

![image](https://user-images.githubusercontent.com/585681/209087594-07051726-469e-46fd-aefe-917d25e8a8be.png)
