### ISSUE TITLE
Syft - Unable to extract licence information - bug

### ISSUE THREAD

**Issue by patrick-morris** [RiverSafeUK/eze-cli#127]

**Comment by kaabmuhammad** [comment]
https://github.com/anchore/syft/issues/465

Might be helpful

**Comment by Parameshveera** [comment]
![Image](https://user-images.githubusercontent.com/119408357/212030971-fdf4dc6a-2d21-4b89-8eed-edb5191e3d25.png)



![Image](https://user-images.githubusercontent.com/119408357/212031073-264fc984-d9e4-4393-8840-a9e0e4382cf0.png)

Ran the tool against Demos folder

**Comment by Anthony-Mckale** [comment]
lgtm
