### ISSUE TITLE
Fix Azure Pipeline for eze-cli

### ISSUE THREAD

**Issue by Anthony-Mckale** [RiverSafeUK/eze-cli#129]
Unit tests are failing within the pipeline build (results in a 10%) and is failing the percentage gate.

https://dev.azure.com/riversafe/DevSecOps/_build/results?buildId=967&view=logs&j=1ebc38c8-fade-5a89-24da-f796855a97f6&t=7e545587-1914-5048-c05b-92ed6ea139f6&l=990

**Comment by shyamriversafe** [comment]
Test cases are failing at following lines in the files java.py and node.py
```async def run_mvn_command(mvn_command: str, cwd: str) -> tuple[CompletedProcess, bool]:```
```async def run_npm_command(npm_command: str, cwd: str) -> tuple[CompletedProcess, bool]:```

**Comment by shyamriversafe** [comment]
possible solution 
use the typing.Tuple 
```
from typing import Tuple

async def run_mvn_command(mvn_command: str, cwd: str) -> Tuple[CompletedProcess, bool]:
```

**Comment by kaabmuhammad** [comment]
https://github.com/RiverSafeUK/eze-cli/pull/134

**Comment by Anthony-Mckale** [comment]
No working crazy hours

:)

9 to 5 is better for your health
