### ISSUE TITLE
create docker image to create linux executable (see #121)

### ISSUE THREAD

**Issue by Anthony-Mckale** [RiverSafeUK/eze-cli#130]

**Comment by Liam-Kearney** [comment]
Dabbled in a few commands:

build-exe-onedir-linux:
	docker run --rm -v $(PWD):/path -w /path python:3.10.9-alpine pip install pyinstaller && pyinstaller --onedir eze/__main__.py -n $(EXE_NAME)

build-exe-onefile-linux:
	docker run --rm -v $(PWD):/path -w /path python:3.10.9-alpine pip install pyinstaller && pyinstaller --onefile eze/__main__.py -n $(EXE_NAME)

**Comment by Anthony-Mckale** [comment]
![image](https://user-images.githubusercontent.com/585681/211050501-f9aff67f-8028-4ac4-a4a8-dfff3abfc35c.png)

**Comment by Anthony-Mckale** [comment]
make build-exes
