### ISSUE TITLE
Cli: Optimise exe builds (reduce size i.e. don't package in dev dependencies)

### ISSUE THREAD

**Issue by Anthony-Mckale** [RiverSafeUK/eze-cli#142]
Have a look at the pyinstaller documentation so you can update the 'build-exe' command in the Makefile so to exclude unnecessary directories such as tests and requirements-dev.txt

**Comment by jnooriRS** [comment]
Looked into creating a spec file where I will remove the directories.
Filter our using the Analysis.data  

[source for help](https://github.com/pyinstaller/pyinstaller/discussions/6126)

**Comment by Parameshveera** [comment]
Since the __main__.py or any subsequent modules (imported thereafter) are not importing the tests folder or 'requirements.txt' etc, we won't be able to cut down the size of .exe by deleting them, since it's not included in building exe

**Comment by jnooriRS** [comment]
And just to confirm the only way to remove folders, dependencies is using the rm-module command according to pyinstaller.

**Comment by Parameshveera** [comment]
@jnoori31 : I saw '--exclude-module' as a part of the pyinstaller command in case we need to remove modules, although that scenario is unlikely to be used often.

**Comment by Anthony-Mckale** [comment]
reviewed this

two ways to reduce size:

- ensure virtual environment is being used when using pyinstaller was able to reduce executable size locally by 10mb that way
- review dependencies for large ones, botocore in particular is very very large at ~70% of the executables uncompressed size
  removing botocore reduces by further 10mb

![image](https://user-images.githubusercontent.com/585681/212907106-e1c16739-a3a3-43e6-8e89-2571943ec968.png)

total possible reduce would be to 33% of 35mb currently being posted. 

https://github.com/RiverSafeUK/eze-cli/releases/tag/v1.0.0

**Comment by Anthony-Mckale** [comment]
given review, failing ticket and putting back into sprint backlog

with a bit of refactoring of the botocore (only used by the now used s3 reporter) possible to reduce 35mb to 12mb
