### ISSUE TITLE
KicsTool: enable kics bom support

### ISSUE THREAD

**Issue by Anthony-Mckale** [RiverSafeUK/eze-cli#96]
-m, --bom include bill of materials (BoM) in results output

should output a bom report that is understood by eze

**Comment by mgonzales-rs** [comment]
PR: https://github.com/RiverSafeUK/eze-cli/pull/155

**Comment by mgonzales-rs** [comment]
![image](https://user-images.githubusercontent.com/85571593/213415876-a4c17443-2f81-40b0-8314-6502d4b6abee.png)
